export const ErrorCode = {
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  ACCESS_DENIED: "ACCESS_DENIED",
  UNAUTHORIZED: "UNAUTHORIZED",
  CONFLICT: "CONFLICT",
  GONE: "GONE",
  VALIDATION_ERROR: "VALIDATION_ERROR",
} as const;
